name: react_router
version: 1.0.0
description: "dart bindings for react_router"
homepage: "https://github.com/matthewnitschke/react_router_dart"

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  js: ^0.6.2
  react: ^6.0.1
  over_react: ^4.1.0
